apiVersion: v3
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: myap{{ .Values.service.app }}p
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
